### PR TITLE
Set up sphinx docs and RTD

### PR DESCRIPTION
**Pull request by kevinsa5**
Follow-up to #12, here is a bare-bones sphinx setup.  I also added a gitignore file, or else the build artifacts would start cluttering everything up.

@ajakef since it looks like you already have an RTD account for gemlog, can you enable PR builds?  It's in "admin > advanced settings > build pull requests for this project".  It's a nice feature to have enabled in general, and especially in this case to make sure everything is configured in a way that works on RTD.

### CODE REVIEW

**Comment by ajakef** [comment]
I just set up "Build PRs" in RTD; the current build seems to be basically empty. If you update the current PR or submit a new one, will that change? Or do I need to merge this PR and populate the docs/?

**Comment by kevinsa5** [comment]
@ajakef thanks for setting that up.  The build is failing right now because cython isn't available when installing gemlog: https://readthedocs.org/projects/gemlog/builds/12119856/

Could fix that by either listing cython as a dependency, or disabling it with that environment variable flag in the RTD settings.  Mild preference for me to use the environment variable; cython isn't really needed for building the docs.  If you agree, can you configure that in the RTD settings?

**Comment by ajakef** [comment]
Just added USE_CYTHON as False in RTD. Will that work? I can't get the failed PR-13 to re-build.

**Comment by kevinsa5** [comment]
@ajakef - got it working.  Hit "show all checks", then "Details" next to the RTD status to view the rendered pages.  

Lessons learned:
- RTD doesn't expose environment variables on PR builds, which I suppose makes sense.  I still think cython isn't strictly necessary, but other solutions like having setup.py detect if it's on RTD seems brittle, it's asking for trouble.  I just configured RTD to install cython before installing gemlog.
- Order matters in the RTD yaml file.  List requirements files before the package itself in the `install` section.

Up to you if you want to clean up or flesh out the source files a bit more before merging -- happy to help, let me know if you want me to make any more changes.  I see the version history is already falling behind.

**Pull request merged**
